version: '3.8'
name: securitize-challenge
services:
  secu-dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: secu-db
    networks:
      - myapp-network
  backend:
    build:
      context: ./backend
    ports:
      - 4000:4000
    depends_on:
      - secu-dev-db
    networks:
    - myapp-network
  frontend:
    build:
      context: ./frontend
    ports:
      - 5173:5173
    networks:
      - myapp-network
networks:
  myapp-network:
    driver: bridge